import type { CompareResultsItem, Revision } from '../../types/state';

const getTestData = () => {
  const testData: Revision[] = [
    {
      id: 1,
      revision: 'coconut',
      author: 'johncleese@python.com',
      revisions: [
        {
          result_set_id: 0,
          repository_id: 4,
          revision: 'coconut',
          author: 'johncleese@python.com',
          comments: "you've got no arms left!",
        },
      ],
      revision_count: 1,
      push_timestamp: -592099200,
      repository_id: 4,
    },
    {
      id: 2,
      revision: 'spam',
      author: 'ericidle@python.com',
      revisions: [
        {
          result_set_id: 1,
          repository_id: 1,
          revision: 'spam',
          author: 'ericidle@python.com',
          comments: "it's just a flesh wound",
        },
      ],
      revision_count: 1,
      push_timestamp: -374198400,
      repository_id: 1,
    },
    {
      id: 3,
      revision: 'spamspam',
      author: 'terrygilliam@python.com',
      revisions: [
        {
          result_set_id: 2,
          repository_id: 4,
          revision: 'coconut',
          author: 'terrygilliam@python.com',
          comments: 'What, ridden on a horse?',
        },
      ],
      revision_count: 1,
      push_timestamp: 554515200,
      repository_id: 4,
    },
    {
      id: 4,
      revision: 'spamspamspamandeggs',
      author: 'michaelpalin@python.com',
      revisions: [
        {
          result_set_id: 3,
          repository_id: 77,
          revision: 'spam',
          author: 'michaelpalin@python.com',
          comments:
            "You've got two empty 'alves of coconuts and you're bangin' 'em togetha!",
        },
      ],
      revision_count: 1,
      push_timestamp: 1593820800,
      repository_id: 77,
    },
    {
      id: 5,
      revision: 'spamspamspamspamandeggs',
      author: 'grahamchapman@python.com',
      revisions: [
        {
          result_set_id: 4,
          repository_id: 77,
          revision: 'spam',
          author: 'grahamchapman@python.com',
          comments: 'She turned me into a newt!',
        },
        {
          result_set_id: 4,
          repository_id: 77,
          revision: 'spam',
          author: 'grahamchapman@python.com',
          comments: 'It got better...',
        },
      ],
      revision_count: 1,
      push_timestamp: 1649808000,
      repository_id: 77,
    },
  ];

  const testCompareData: CompareResultsItem[] = [
    {
      framework_id: 1,
      platform: 'macosx1015-64-shippable-qr',
      suite: 'a11yr',
      is_empty: false,
      header_name: 'a11yr dhtml.html opt e10s fission stylo webrender',
      base_repository_name: 'mozilla-central',
      new_repository_name: 'mozilla-central',
      is_complete: true,
      base_measurement_unit: 'ms',
      new_measurement_unit: 'ms',
      base_retriggerable_job_ids: [381594973],
      new_retriggerable_job_ids: [381452501],
      base_runs: [704.84],
      new_runs: [712.44],
      base_avg_value: 704.84,
      new_avg_value: 712.44,
      base_median_value: 704.84,
      new_median_value: 712.44,
      test: 'dhtml.html',
      option_name: 'opt',
      extra_options: 'e10s fission stylo webrender',
      base_stddev: 0.0,
      new_stddev: 0.0,
      base_stddev_pct: 0.0,
      new_stddev_pct: 0.0,
      confidence: 0.05,
      confidence_text: 'low',
      confidence_text_long:
        "Result of running t-test on base versus new result distribution: A value of 'low' suggests less confidence that there is a sustained, significant change between the two revisions.",
      t_value_confidence: 5,
      t_value_care_min: 3,
      graphs_link:
        'https://treeherder.mozilla.org/perfherder/graphs?highlightedRevisions=1e32960788ea&highlightedRevisions=6a1f133815a1&series=mozilla-central%2C9daea6258ae244039eb2390f3eab7935994cbb0e%2C1%2C1&timerange=5184000',
      delta_value: 7.6,
      delta_percentage: 1.08,
      magnitude: 5.39,
      new_is_better: false,
      is_confident: false,
      more_runs_are_needed: true,
      noise_metric: false,
      is_improvement: true,
      is_regression: false,
      is_meaningful: true,
    },
    {
      framework_id: 1,
      platform: 'linux1804-64-shippable-qr',
      suite: 'a11yr',
      is_empty: false,
      header_name: 'a11yr dhtml.html opt e10s fission stylo webrender',
      base_repository_name: 'mozilla-central',
      new_repository_name: 'mozilla-central',
      is_complete: true,
      base_measurement_unit: 'ms',
      new_measurement_unit: 'ms',
      base_retriggerable_job_ids: [381587080],
      new_retriggerable_job_ids: [381451522],
      base_runs: [776.97],
      new_runs: [791.34],
      base_avg_value: 776.97,
      new_avg_value: 791.34,
      base_median_value: 776.97,
      new_median_value: 791.34,
      test: 'dhtml.html',
      option_name: 'opt',
      extra_options: 'e10s fission stylo webrender',
      base_stddev: 0.0,
      new_stddev: 0.0,
      base_stddev_pct: 0.0,
      new_stddev_pct: 0.0,
      confidence: 0.09,
      confidence_text: 'med',
      confidence_text_long:
        "Result of running t-test on base versus new result distribution: A value of 'low' suggests less confidence that there is a sustained, significant change between the two revisions.",
      t_value_confidence: 5,
      t_value_care_min: 3,
      graphs_link:
        'https://treeherder.mozilla.org/perfherder/graphs?highlightedRevisions=1e32960788ea&highlightedRevisions=6a1f133815a1&series=mozilla-central%2Cedcc6311f15bdf7924ef3f0ccfd8b47ce1892212%2C1%2C1&timerange=5184000',
      delta_value: 14.37,
      delta_percentage: 1.85,
      magnitude: 9.25,
      new_is_better: false,
      is_confident: false,
      more_runs_are_needed: true,
      noise_metric: false,
      is_improvement: false,
      is_regression: true,
      is_meaningful: true,
    },
    {
      framework_id: 1,
      platform: 'windows10-64-shippable-qr',
      suite: 'a11yr',
      is_empty: false,
      header_name: 'a11yr dhtml.html opt e10s fission stylo webrender',
      base_repository_name: 'mozilla-central',
      new_repository_name: 'mozilla-central',
      is_complete: true,
      base_measurement_unit: 'ms',
      new_measurement_unit: 'ms',
      base_retriggerable_job_ids: [381588467],
      new_retriggerable_job_ids: [381453172],
      base_runs: [643.54],
      new_runs: [628.09],
      base_avg_value: 643.54,
      new_avg_value: 628.09,
      base_median_value: 643.54,
      new_median_value: 628.09,
      test: 'dhtml.html',
      option_name: 'opt',
      extra_options: 'e10s fission stylo webrender',
      base_stddev: 0.0,
      new_stddev: 0.0,
      base_stddev_pct: 0.0,
      new_stddev_pct: 0.0,
      confidence: 0.11,
      confidence_text: 'high',
      confidence_text_long:
        "Result of running t-test on base versus new result distribution: A value of 'low' suggests less confidence that there is a sustained, significant change between the two revisions.",
      t_value_confidence: 5,
      t_value_care_min: 3,
      graphs_link:
        'https://treeherder.mozilla.org/perfherder/graphs?highlightedRevisions=1e32960788ea&highlightedRevisions=6a1f133815a1&series=mozilla-central%2C3a6d4b6178678c3113c980b378bb83b2629926a0%2C1%2C1&timerange=5184000',
      delta_value: -15.46,
      delta_percentage: -2.4,
      magnitude: 12.01,
      new_is_better: true,
      is_confident: false,
      more_runs_are_needed: true,
      noise_metric: false,
      is_improvement: false,
      is_regression: false,
      is_meaningful: true,
    },
    {
      framework_id: 1,
      platform: 'windows10-64-shippable-qr',
      suite: 'a11yr',
      is_empty: false,
      header_name: 'a11yr dhtml.html opt e10s fission stylo webrender',
      base_repository_name: 'mozilla-central',
      new_repository_name: 'mozilla-central',
      is_complete: true,
      base_measurement_unit: 'ms',
      new_measurement_unit: 'ms',
      base_retriggerable_job_ids: [381588467],
      new_retriggerable_job_ids: [381453172],
      base_runs: [643.54],
      new_runs: [628.09],
      base_avg_value: 643.54,
      new_avg_value: 628.09,
      base_median_value: 643.54,
      new_median_value: 628.09,
      test: 'dhtml.html',
      option_name: 'opt',
      extra_options: 'e10s fission stylo webrender',
      base_stddev: 0.0,
      new_stddev: 0.0,
      base_stddev_pct: 0.0,
      new_stddev_pct: 0.0,
      confidence: 0.11,
      confidence_text: null,
      confidence_text_long:
        "Result of running t-test on base versus new result distribution: A value of 'low' suggests less confidence that there is a sustained, significant change between the two revisions.",
      t_value_confidence: 5,
      t_value_care_min: 3,
      graphs_link:
        'https://treeherder.mozilla.org/perfherder/graphs?highlightedRevisions=1e32960788ea&highlightedRevisions=6a1f133815a1&series=mozilla-central%2C3a6d4b6178678c3113c980b378bb83b2629926a0%2C1%2C1&timerange=5184000',
      delta_value: -15.46,
      delta_percentage: -2.4,
      magnitude: 12.01,
      new_is_better: true,
      is_confident: false,
      more_runs_are_needed: true,
      noise_metric: false,
      is_improvement: false,
      is_regression: false,
      is_meaningful: true,
    },
  ];
  return { testCompareData, testData };
};
export default getTestData;
