export const comparisonResults = [
  {
    base_retriggerable_job_ids: [1, 2],
    new_retriggerable_job_ids: [0, 1],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-shippable-qr',
    suite: 'wikipedia',
    framework_id: 0,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 50,    
    new_is_better: true,
    confidence: 60,
    confidence_text: 'low',
    is_improvement: true,
    is_regression: false,
    is_meaningful: false,
    test: 'fcp',
  },
  {
    base_retriggerable_job_ids: [0, 3],
    new_retriggerable_job_ids: [2, 4],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'macosx1015-64-shippable-qr',
    suite: 'instagram',
    framework_id: 1,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 1,
    delta : 0.0,    
    new_is_better: true,
    confidence: 60,
    confidence_text: 'low',
    is_improvement: false,
    is_regression: false,
    is_meaningful: false,
    test: 'fnbpaint',
  },
  {
    base_retriggerable_job_ids: [0, 3],
    new_retriggerable_job_ids: [3, 5],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-qr',
    suite: 'instagram',
    framework_id: 2,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 100,
    new_avg_value: 300,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 2,
    delta : -50,    
    new_is_better: true,
    confidence: 60,
    confidence_text: 'low',
    is_improvement: false,
    is_regression: false,
    is_meaningful: false,
    test: 'loadtime',
  },
  {
    base_retriggerable_job_ids: [0, 6],
    new_retriggerable_job_ids: [4, 7],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-qr',
    suite: 'amazon',
    framework_id: 1,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 3,
    delta : -50,    
    new_is_better: true,
    confidence: 60,
    confidence_text: 'low',
    is_improvement: false,
    is_regression: false,
    is_meaningful: false,
    test: 'dcf',
  },
  {
    base_retriggerable_job_ids: [0, 7],
    new_retriggerable_job_ids: [5, 9],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-qr',
    suite: 'google-suite',
    framework_id: 5,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: true,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 6,
    delta : -100,    
    new_is_better: true,
    confidence: 60,
    confidence_text: 'low',
    is_improvement: true,
    is_regression: false,
    is_meaningful: false,
    test: 'dcf',
  },
  {
    base_retriggerable_job_ids: [0, 8],
    new_retriggerable_job_ids: [6, 8],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-qr',
    suite: 'bing-search',
    framework_id: 6,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: true,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 8,
    delta : 1000,    
    new_is_better: true,
    confidence: 60,
    confidence_text: 'medium',
    is_improvement: false,
    is_regression: false,
    is_meaningful: false,
    test: 'loadtime',
  },
  {
    base_retriggerable_job_ids: [0, 4],
    new_retriggerable_job_ids: [7, 0],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'windows10-64-shippable-qr',
    suite: 'fandom',
    framework_id: 6,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: true,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 10,
    delta : 10,    
    new_is_better: true,
    confidence: 40,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: false,
    is_meaningful: false,
    test: 'fcp',
  },
  {
    base_retriggerable_job_ids: [0, 6],
    new_retriggerable_job_ids: [7, 8],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'windows10-64-shippable-qr',
    suite: 'fandom',
    framework_id: 6,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 34,
    delta : 10,    
    new_is_better: true,
    confidence: 40,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: false,
    is_meaningful: false,
    test: 'fnbpaint',
  },
  {
    base_retriggerable_job_ids: [0, 4],
    new_retriggerable_job_ids: [10, 0],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-shippable-qr',
    suite: 'fandom',
    framework_id: 8,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: true,
    confidence: 400,
    confidence_text: 'medium',
    is_improvement: true,
    is_regression: true,
    is_meaningful: true,
    test: 'dcf',
  },
  {
    base_retriggerable_job_ids: [0, 3],
    new_retriggerable_job_ids: [11, 12],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'macosx1015-64-shippable-qr',
    suite: 'yahoo-mail',
    framework_id: 9,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: true,
    confidence: 40,
    confidence_text: 'medium',
    is_improvement: true,
    is_regression: true,
    is_meaningful: true,
    test: 'loadtime',
  },
  {
    base_retriggerable_job_ids: [0, 6],
    new_retriggerable_job_ids: [15, 16],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'macosx1015-64-shippable-qr',
    suite: 'twitter',
    framework_id: 11,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: true,
    confidence: 4,
    confidence_text: 'medium',
    is_improvement: true,
    is_regression: true,
    is_meaningful: true,
    test: 'ContentfulSpeedIndex',
  },
  {
    base_retriggerable_job_ids: [0, 70],
    new_retriggerable_job_ids: [16, 35],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'macosx1015-64-shippable-qr',
    suite: 'youtube-watch',
    framework_id: 6,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: true,
    confidence: 4,
    confidence_text: 'medium',
    is_improvement: true,
    is_regression: true,
    is_meaningful: true,
    test: 'ContentfulSpeedIndex',
  },
  {
    base_retriggerable_job_ids: [0, 40],
    new_retriggerable_job_ids: [234, 432],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'macosx1015-64-shippable-qr',
    suite: 'amazon-search',
    framework_id: 7,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: true,
    confidence: 4,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: true,
    is_meaningful: true,
    test: 'PerceptualSpeedIndex',
  },
  {
    base_retriggerable_job_ids: [0, 888],
    new_retriggerable_job_ids: [19, 56],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-qr',
    suite: 'google-search',
    framework_id: 8,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: false,
    confidence: 4,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: true,
    is_meaningful: true,
    test: 'SpeedIndex',
  }, 
  {
    base_retriggerable_job_ids: [4, 5],
    new_retriggerable_job_ids: [19, 34],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-clang-trunk-qr',
    suite: 'netflix',
    framework_id: 5,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: false,
    confidence: 4,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: true,
    is_meaningful: true,
    test: 'FirstVisualChange',
  },
  {
    base_retriggerable_job_ids: [0, 45],
    new_retriggerable_job_ids: [120, 455],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-qr',
    suite: 'google-search',
    framework_id: 100,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: false,
    confidence: -4,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: true,
    is_meaningful: true,
    test: 'LastVisualChange',
  },
  {
    base_retriggerable_job_ids: [123, 345],
    new_retriggerable_job_ids: [199, 345],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'windows10-64-shippable-qr',
    suite: 'google-search',
    framework_id: 8,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: false,
    confidence: 4,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: true,
    is_meaningful: true,
    test: 'dcf',
  },
  {
    base_retriggerable_job_ids: [0, 56],
    new_retriggerable_job_ids: [109, 567],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-qr',
    suite: 'google-search',
    framework_id: 6,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 0.0,
    new_avg_value: 0.0,
    base_stddev: 0,
    new_stddev: 0,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: false,
    confidence: 4,
    confidence_text: 'high',
    is_improvement: false,
    is_regression: true,
    is_meaningful: true,
    test: 'fcp',
  },
  {
    base_retriggerable_job_ids: [0, 990],
    new_retriggerable_job_ids: [1900, 990],
    base_measurement_unit: 'ms',
    new_measurement_unit: 'ms',
    platform: 'linux1804-64-shippable-qr',
    suite: 'instagram',
    framework_id: 9,
    new_repository_name: 'try',
    base_repository_name: 'try',
    new_runs: [],
    base_runs: [],
    is_complete: false,
    base_avg_value: 9.0,
    new_avg_value: 8.0,
    base_stddev: 0.22,
    new_stddev: 0.33,
    base_stddev_pct: 0,
    new_stddev_pct: 0,
    delta : 10,    
    new_is_better: false,
    confidence: 4,
    confidence_text: 'low',
    is_improvement: false,
    is_regression: true,
    is_meaningful: true,
    test: 'fcp',
  },
];
